---

- name: Copy GPG Files
  copy:
    src: "{{ gpg_core_files_dir }}/"
    dest: "{{ gpg_core_files_remote_dir }}"

- name: Check if Project Exists
  command: >
    oc get project {{ openshift_image_management_project_name }}
  ignore_errors: true
  register: signer_project_exists

- name: Create OpenShift Project
  command: >
    oc adm new-project {{ openshift_image_management_project_name }} --display-name="{{ openshift_image_management_project_display_name }}"
  when: signer_project_exists.rc != 0

- name: Label Image Signer Nodes
  command: >
    oc label node {{ item }} {{ openshift_image_management_node_label }} --overwrite=true
  with_items: "{{ groups[ image_managers_hostgroup ] }}"

- name: Taint Image Signer Nodes
  command: >
    oc adm taint nodes {{ item }} {{ openshift_image_management_node_taint }} --overwrite=true
  with_items: "{{ groups[ image_managers_hostgroup ] }}"

- name: Check if GPG Secret Exists
  command: >
    oc get secret {{ openshift_image_management_gpg_secret_name }} -n {{ openshift_image_management_project_name }}
  ignore_errors: yes
  register: signer_secret_exists

- name: Delete GPG Secret
  command: >
    oc delete secret {{ openshift_image_management_gpg_secret_name }} -n {{ openshift_image_management_project_name }}
  when: signer_secret_exists.rc == 0

- name: Create GPG Secret
  command: >
    oc secret new {{ openshift_image_management_gpg_secret_name }} {{ gpg_core_files_remote_dir }} -n {{ openshift_image_management_project_name }}

- name: Copy OpenShift Configurations
  copy:
    src: "{{ item }}"
    dest: "{{ openshift_configs_dest_dir }}/"
  with_items: "{{ openshift_configs }}"

- name: Configure Privileged SCC
  command: >
    oc adm policy add-scc-to-user privileged  -n {{ openshift_image_management_project_name }} -z {{ openshift_image_management_sa_name }}

- name: Instantiate OpenShift Templates
  shell: "{{ item }}"
  with_items:
    - "oc process -p NAMESPACE={{ openshift_image_management_project_name }} -p SERVICE_ACCOUNT_NAME={{ openshift_image_management_sa_name }} -f {{ openshift_configs_dest_dir }}/{{ openshift_policy_template }} | oc apply -n {{ openshift_image_management_project_name }} -f-"
    - "oc apply -n {{ openshift_image_management_project_name }} -f {{ openshift_configs_dest_dir }}/{{ openshift_sign_image_template }}"
    - "oc apply -n {{ openshift_image_management_project_name }} -f {{ openshift_configs_dest_dir }}/{{ openshift_sign_image_pod_template }}"
    - "oc apply -n {{ openshift_image_management_project_name }} -f {{ openshift_configs_dest_dir }}/{{ openshift_scan_image_pod_template }}"
    - "oc process -p NAMESPACE={{ openshift_image_management_project_name }} -p VERSION={{ openshift_version }} -f {{ openshift_configs_dest_dir }}/{{ openshift_base_scan_template }} | oc apply -n {{ openshift_image_management_project_name }} -f-"

- name: Instantiate OpenShift Templates (Event Controller)
  shell: "{{ item }}"
  with_items:
    - "oc process -p NAMESPACE={{ openshift_image_management_project_name }} -f {{ openshift_configs_dest_dir }}/{{ openshift_event_controller_template }} | oc apply -n {{ openshift_image_management_project_name }} -f-"
  when: deploy_eventcontroller

- name: Remove Configuration Directories
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - "{{ gpg_core_files_remote_dir }}"
    - "{{ openshift_configs_dest_dir }}"

- name: Export Default Project Template
  shell: >
    oc adm create-bootstrap-project-template -o yaml > {{ tmp_default_project_template }}

- name: Modify Default Project Template
  lineinfile:
    dest: "{{ tmp_default_project_template }}"
    insertbefore: "^parameters:"
    line: "{{ lookup('template', 'signature-viewer-default-template.j2') }}"

- name: Apply Default Project Template
  command: >
    oc apply -n default -f {{ tmp_default_project_template }}

- name: Remove Default Project Template File
  file:
    state: absent
    path: "{{ tmp_default_project_template }}"

- name: Update Master Configuration
  become: true
  lineinfile:
    line: '  projectRequestTemplate: "default/project-request"'
    regexp: '  projectRequestTemplate:'
    path: /etc/origin/master/master-config.yaml
  delegate_to: "{{ item }}"
  with_items: "{{ groups.masters }}"
  register: master_config_result

- name: Restart Master Service
  become: true
  service:
    name: "{{ (groups['masters']|length|int > 1 or openshift_version | float >= 3.7) | ternary('atomic-openshift-master-api','atomic-openshift-master') }}"
    state: restarted
  delegate_to: "{{ item['_ansible_delegated_vars']['ansible_delegated_host'] }}"
  with_items: "{{ master_config_result.results }}"
  register: restart_masters
  when: item.changed

- name: Pause to let Master Service Come Back Online
  pause:
    seconds: 10
  when: restart_masters.changed

- name: Sign Base Signer Scanner Image
  block:
    - name: "Check ImageStream Status"
      command: >
        oc get is image-sign-scan-base -n {{ openshift_image_management_project_name }} -o json
      register: is_json
      until: (is_json.stdout | from_json)['status']['tags'] is defined and (is_json.stdout | from_json)['status']['tags'] | length > 0
      retries: 40
      delay: 10

    - name: Query Image
      command: >
        oc get image {{ (is_json.stdout | from_json)['status']['tags'][0]['items'][0]['image'] }} -o json
      register: query_image_output

    - name: Instantiate Signing Pod
      shell: oc process {{ openshift_image_management_project_name }}//{{ openshift_sign_pod_template_name }} -p IMAGE_TO_SIGN={{ (is_json.stdout | from_json)['status']['tags'][0]['items'][0]['dockerImageReference'].split('@')[0] }}:{{ (is_json.stdout | from_json)['status']['tags'][0]['tag'] }} -p IMAGE_DIGEST={{ (is_json.stdout | from_json)['status']['tags'][0]['items'][0]['image'] }} -p SIGN_BY={{ gpg_publickey_file }} | oc apply -n {{ openshift_image_management_project_name }} -f-
      when: (query_image_output.stdout | from_json)['signatures'] is not defined
  when: not deploy_eventcontroller


